// Generate 150+ problems across categories
const generateProblems = () => {
  const categories = ['Arrays', 'Strings', 'LinkedLists', 'Trees'];
  const problems = [];
  let id = 1;

  const arrayProblems = [
    { title: 'Two Sum', desc: 'Find two numbers that add up to target' },
    { title: 'Best Time to Buy and Sell Stock', desc: 'Maximize profit from stock transactions' },
    { title: 'Contains Duplicate', desc: 'Check if array contains duplicates' },
    { title: 'Product of Array Except Self', desc: 'Return product array without division' },
    { title: 'Maximum Subarray', desc: 'Find contiguous subarray with largest sum' },
    { title: 'Rotate Array', desc: 'Rotate array right by k steps' },
    { title: 'Search in Rotated Sorted Array', desc: 'Search in rotated sorted array' },
    { title: 'Median of Two Sorted Arrays', desc: 'Find median of two sorted arrays' },
    { title: 'Container With Most Water', desc: 'Find two lines containing most water' },
    { title: '3Sum', desc: 'Find three numbers that sum to target' },
    { title: 'Remove Duplicates from Sorted Array', desc: 'Remove duplicates in-place' },
    { title: 'Move Zeroes', desc: 'Move all zeroes to end' },
    { title: 'Plus One', desc: 'Add one to number represented as array' },
    { title: 'Majority Element', desc: 'Find element appearing more than n/2 times' },
    { title: 'Missing Number', desc: 'Find missing number in array' },
    { title: 'Single Number', desc: 'Find single number in array of pairs' },
    { title: 'Intersection of Two Arrays', desc: 'Find common elements' },
    { title: 'Valid Sudoku', desc: 'Validate sudoku board' },
    { title: 'Set Matrix Zeroes', desc: 'Set entire row/column to zero' },
    { title: 'Game of Life', desc: 'Simulate game of life' },
    { title: 'Spiral Matrix', desc: 'Traverse matrix in spiral order' },
    { title: 'Search a 2D Matrix', desc: 'Search in sorted 2D matrix' },
    { title: 'Kth Largest Element', desc: 'Find kth largest element' },
    { title: 'Top K Frequent Elements', desc: 'Find k most frequent elements' },
    { title: 'Merge Intervals', desc: 'Merge overlapping intervals' },
    { title: 'Insert Interval', desc: 'Insert new interval in list' },
    { title: 'First Missing Positive', desc: 'Find first missing positive' },
    { title: 'Jump Game', desc: 'Determine if can reach last index' },
    { title: 'Jump Game II', desc: 'Find minimum jumps to reach end' },
    { title: 'Gas Station', desc: 'Find starting gas station' },
  ];

  const stringProblems = [
    { title: 'Valid Parentheses', desc: 'Check if parentheses are valid' },
    { title: 'Reverse String', desc: 'Reverse a string array' },
    { title: 'Reverse Integer', desc: 'Reverse integer digits' },
    { title: 'First Unique Character', desc: 'Find first non-repeating character' },
    { title: 'Valid Anagram', desc: 'Check if strings are anagrams' },
    { title: 'Longest Substring Without Repeating', desc: 'Find longest substring without repeats' },
    { title: 'Longest Palindromic Substring', desc: 'Find longest palindromic substring' },
    { title: 'String to Integer (atoi)', desc: 'Convert string to integer' },
    { title: 'Palindrome Number', desc: 'Check if number is palindrome' },
    { title: 'Is Palindrome', desc: 'Check if string is palindrome' },
    { title: 'Group Anagrams', desc: 'Group anagrams together' },
    { title: 'Word Pattern', desc: 'Check if pattern matches string' },
    { title: 'Isomorphic Strings', desc: 'Check if strings are isomorphic' },
    { title: 'Word Ladder', desc: 'Find shortest word ladder' },
    { title: 'Implement strStr()', desc: 'Find substring in string' },
    { title: 'Ransom Note', desc: 'Check if ransom note can be formed' },
    { title: 'Happy Number', desc: 'Determine if number is happy' },
    { title: 'Valid IP Address', desc: 'Validate IP address format' },
    { title: 'Rotate String', desc: 'Check if s can be rotated to t' },
    { title: 'Backspace String Compare', desc: 'Compare strings with backspace' },
    { title: 'Decode String', desc: 'Decode encoded string' },
    { title: 'Encode and Decode Strings', desc: 'Encode/decode list of strings' },
    { title: 'Longest Common Prefix', desc: 'Find longest common prefix' },
    { title: 'Remove Duplicate Letters', desc: 'Remove duplicates preserving order' },
    { title: 'Multiply Strings', desc: 'Multiply two strings as numbers' },
    { title: 'Add Strings', desc: 'Add two strings as numbers' },
    { title: 'Compare Version Numbers', desc: 'Compare version strings' },
    { title: 'Reorder Log Files', desc: 'Reorder logs by criteria' },
    { title: 'Minimum Window Substring', desc: 'Find minimum window with chars' },
    { title: 'Permutation in String', desc: 'Check if permutation exists' },
  ];

  const linkedListProblems = [
    { title: 'Reverse Linked List', desc: 'Reverse a linked list' },
    { title: 'Merge Two Sorted Lists', desc: 'Merge two sorted linked lists' },
    { title: 'Remove Nth Node', desc: 'Remove nth node from end' },
    { title: 'Linked List Cycle', desc: 'Detect cycle in linked list' },
    { title: 'Intersection of Two Lists', desc: 'Find intersection point' },
    { title: 'Palindrome Linked List', desc: 'Check if list is palindrome' },
    { title: 'Middle of Linked List', desc: 'Find middle node of list' },
    { title: 'Add Two Numbers', desc: 'Add two numbers as lists' },
    { title: 'Reorder List', desc: 'Reorder list as L0->Ln->L1->Ln-1' },
    { title: 'LRU Cache', desc: 'Implement LRU cache' },
    { title: 'Copy List with Random Pointer', desc: 'Deep copy list with random' },
    { title: 'Sort List', desc: 'Sort linked list' },
    { title: 'Merge k Sorted Lists', desc: 'Merge k sorted lists' },
    { title: 'Swap Nodes in Pairs', desc: 'Swap adjacent nodes in pairs' },
    { title: 'Remove Duplicates', desc: 'Remove duplicate nodes' },
    { title: 'Split Linked List', desc: 'Split list in two halves' },
    { title: 'Delete Node', desc: 'Delete given node without head' },
    { title: 'Reverse Between', desc: 'Reverse list between positions' },
    { title: 'Rotate List', desc: 'Rotate list right by k' },
    { title: 'Partition List', desc: 'Partition list around value' },
    { title: 'Remove Elements', desc: 'Remove all nodes with value' },
    { title: 'Odd Even Linked List', desc: 'Group odd/even positioned nodes' },
    { title: 'Reverse k Group', desc: 'Reverse nodes in k group' },
    { title: 'Flatten Multilevel List', desc: 'Flatten multilevel linked list' },
    { title: 'Insert into Sorted List', desc: 'Insert into sorted circular list' },
    { title: 'Next Greater Node', desc: 'Find next greater value' },
    { title: 'Remove Zero Sum', desc: 'Remove zero sum consecutive' },
    { title: 'Maximum Twin Sum', desc: 'Find maximum twin sum' },
    { title: 'Swapping Nodes', desc: 'Swap nodes at positions' },
    { title: 'Linked List Components', desc: 'Find number of components' },
  ];

  const treeProblems = [
    { title: 'Maximum Depth of Binary Tree', desc: 'Find maximum depth' },
    { title: 'Balanced Binary Tree', desc: 'Check if tree is balanced' },
    { title: 'Invert Binary Tree', desc: 'Invert/mirror the tree' },
    { title: 'Same Tree', desc: 'Check if two trees are same' },
    { title: 'Symmetric Tree', desc: 'Check if tree is symmetric' },
    { title: 'Path Sum', desc: 'Check if path with sum exists' },
    { title: 'Binary Tree Level Order', desc: 'Level order traversal' },
    { title: 'Lowest Common Ancestor', desc: 'Find LCA of two nodes' },
    { title: 'Binary Search Tree Iterator', desc: 'Implement BST iterator' },
    { title: 'Validate Binary Search Tree', desc: 'Check if tree is valid BST' },
    { title: 'Recover Binary Search Tree', desc: 'Recover two swapped nodes' },
    { title: 'Serialize Deserialize', desc: 'Serialize and deserialize tree' },
    { title: 'Binary Tree Paths', desc: 'Find all root to leaf paths' },
    { title: 'Diameter of Binary Tree', desc: 'Find diameter of tree' },
    { title: 'Minimum Depth', desc: 'Find minimum depth' },
    { title: 'Sum Root to Leaf Numbers', desc: 'Sum numbers from paths' },
    { title: 'Construct Binary Tree', desc: 'Build tree from inorder/preorder' },
    { title: 'Kth Smallest in BST', desc: 'Find kth smallest element' },
    { title: 'Range Sum in BST', desc: 'Sum values in range' },
    { title: 'Minimum Absolute Difference', desc: 'Find minimum abs difference' },
    { title: 'All Elements in Two BSTs', desc: 'Get all elements in sorted' },
    { title: 'Trim Binary Search Tree', desc: 'Trim tree to range' },
    { title: 'Average of Levels', desc: 'Find average at each level' },
    { title: 'Rightmost Node at Each Level', desc: 'Get rightmost node' },
    { title: 'Maximum Path Sum', desc: 'Find maximum path sum' },
    { title: 'Largest Values in Rows', desc: 'Find largest in each row' },
    { title: 'Vertical Order Traversal', desc: 'Vertical order traversal' },
    { title: 'Delete Node in BST', desc: 'Delete node from BST' },
    { title: 'Binary Tree Coloring', desc: 'Color tree based on rules' },
    { title: 'Maximum Product Path', desc: 'Find maximum product path' },
  ];

  const allProblems = [
    ...arrayProblems.map(p => ({ ...p, category: 'Arrays' })),
    ...stringProblems.map(p => ({ ...p, category: 'Strings' })),
    ...linkedListProblems.map(p => ({ ...p, category: 'LinkedLists' })),
    ...treeProblems.map(p => ({ ...p, category: 'Trees' })),
  ];

  return allProblems.map((p, idx) => ({
    id: String(idx + 1),
    title: p.title,
    slug: p.title.toLowerCase().replace(/\s+/g, '-'),
    category: p.category,
    description: p.desc,
    solved: Math.floor(Math.random() * 120) + 10,
    submissions: Math.floor(Math.random() * 200) + 50,
  }));
};

export const mockProblems = generateProblems();

export const mockUsers = [
  { id: '1', username: 'Rajesh Kumar', email: 'rajesh@example.com', solved: 50, submissions: 95, acceptance: 52.6, streak: 50 },
  { id: '2', username: 'Priya Sharma', email: 'priya@example.com', solved: 50, submissions: 92, acceptance: 54.3, streak: 48 },
  { id: '3', username: 'Arjun Patel', email: 'arjun@example.com', solved: 50, submissions: 91, acceptance: 54.9, streak: 45 },
  { id: '4', username: 'Sunita Reddy', email: 'sunita@example.com', solved: 50, submissions: 88, acceptance: 56.8, streak: 42 },
  { id: '5', username: 'Vikram Singh', email: 'vikram@example.com', solved: 50, submissions: 86, acceptance: 58.1, streak: 40 },
  { id: '6', username: 'Divya Nair', email: 'divya@example.com', solved: 50, submissions: 84, acceptance: 59.5, streak: 38 },
  { id: '7', username: 'Aditya Gupta', email: 'aditya@example.com', solved: 50, submissions: 82, acceptance: 61.0, streak: 35 },
  { id: '8', username: 'Neha Iyer', email: 'neha@example.com', solved: 50, submissions: 79, acceptance: 63.3, streak: 32 },
  { id: '9', username: 'Rohan Desai', email: 'rohan@example.com', solved: 50, submissions: 77, acceptance: 64.9, streak: 28 },
  { id: '10', username: 'Ananya Rao', email: 'ananya@example.com', solved: 50, submissions: 75, acceptance: 66.7, streak: 25 },
];

export const mockActivityData = [
  { date: '2024-01-01', submissions: 12 },
  { date: '2024-01-02', submissions: 8 },
  { date: '2024-01-03', submissions: 15 },
  { date: '2024-01-04', submissions: 0 },
  { date: '2024-01-05', submissions: 11 },
  { date: '2024-01-06', submissions: 14 },
  { date: '2024-01-07', submissions: 9 },
  { date: '2024-01-08', submissions: 17 },
  { date: '2024-01-09', submissions: 10 },
  { date: '2024-01-10', submissions: 13 },
];

export const mockContests = [
  {
    id: 'contest-1',
    title: 'contest-1',
    startTime: new Date(Date.now() + 3600000),
    duration: 90,
    problems: 4,
    registered: 36,
    status: 'upcoming',
    description: 'Admin-created coding contest with 4 questions and auto-judging.',
    timeLimit: 2,
    problemTypes: ['Arrays', 'Strings', 'Math', 'Greedy'],
    prizePoolCoins: 2000,
    prizes: [
      { rank: '1st', coins: 1000 },
      { rank: '2nd', coins: 600 },
      { rank: '3rd', coins: 400 },
    ],
  },
];

export const contestProblems = {
  'contest-1': [
    {
      id: 'c1-q1',
      title: 'Array Sum',
      category: 'Arrays',
      description: 'Read n and then n integers. Print the sum.',
      constraints: '1 <= n <= 1000, -10^4 <= a[i] <= 10^4',
      examples: [
        { input: '5\n1 2 3 4 5', output: '15' },
      ],
      testCases: [
        { input: '4\n1 2 3 4', output: '10', hidden: false },
        { input: '4\n2 3 4 9', output: '18', hidden: true },
        { input: '5\n10 20 30 40 50', output: '150', hidden: true },
        { input: '3\n-1 2 7', output: '8', hidden: true },
        { input: '6\n1 1 1 1 1 1', output: '6', hidden: true },
      ],
    },
    {
      id: 'c1-q2',
      title: 'Reverse Word',
      category: 'Strings',
      description: 'Given a single word, print it in reverse.',
      constraints: '1 <= word length <= 200',
      examples: [
        { input: 'platform', output: 'mroftalp' },
      ],
      testCases: [
        { input: 'platform', output: 'mroftalp', hidden: false },
        { input: 'contest', output: 'tsetnoc', hidden: true },
        { input: 'level', output: 'level', hidden: true },
        { input: 'code', output: 'edoc', hidden: true },
        { input: 'python', output: 'nohtyp', hidden: true },
      ],
    },
    {
      id: 'c1-q3',
      title: 'Even Count',
      category: 'Math',
      description: 'Read n and n integers. Print how many numbers are even.',
      constraints: '1 <= n <= 1000',
      examples: [
        { input: '6\n1 2 3 4 5 6', output: '3' },
      ],
      testCases: [
        { input: '6\n1 2 3 4 5 6', output: '3', hidden: false },
        { input: '5\n7 9 11 13 15', output: '0', hidden: true },
        { input: '4\n8 12 14 16', output: '4', hidden: true },
        { input: '7\n1 3 5 7 2 4 6', output: '3', hidden: true },
        { input: '1\n100', output: '1', hidden: true },
      ],
    },
    {
      id: 'c1-q4',
      title: 'Max Adjacent Difference',
      category: 'Greedy',
      description: 'Read n and n integers. Print maximum absolute difference of adjacent elements.',
      constraints: '2 <= n <= 1000',
      examples: [
        { input: '5\n1 8 3 10 2', output: '8' },
      ],
      testCases: [
        { input: '5\n1 8 3 10 2', output: '8', hidden: false },
        { input: '4\n4 4 4 4', output: '0', hidden: true },
        { input: '6\n2 9 1 7 3 12', output: '9', hidden: true },
        { input: '3\n10 1 20', output: '19', hidden: true },
        { input: '5\n5 2 8 6 9', output: '6', hidden: true },
      ],
    },
  ],
};
